main:
  container_name: main_service_liberty1
  net: ${NETWORK}
  build: ./acmeair-mainapp/
  environment:
    - LICENSE=accept

as:
  container_name: auth_service_liberty1
  net: ${NETWORK}
  build: ./acmeair-as/
  environment:
    - LICENSE=accept

bs:
  container_name: booking_service_liberty1
  net: ${NETWORK}
  build: ./acmeair-bs/
  environment:
    - LICENSE=accept

cs:
  container_name: customer_service_liberty1
  net: ${NETWORK}
  build: ./acmeair-cs/
  environment:
    - LICENSE=accept


fs:
  container_name: flight_service_liberty1
  net: ${NETWORK}
  build: ./acmeair-fs/
  environment:
    - LICENSE=accept


